---
# tasks file for roles/app
  - name: Run Backend-green
    docker_container:
      name: backend-green
      image: krouzet/backendapi
      network_mode: app-network
  
  - name: Run Backend-blue
    docker_container:
      name: backend-blue
      image: krouzet/backendapi
      network_mode: app-network
