version: '3.7'

services:
    backend-blue:
        build:
          context: ./BackendAPI
          dockerfile: Dockerfile
        networks:
          - app-network
        depends_on:
          - database
    
    backend-green:
        build:
          context: ./BackendAPI
          dockerfile: Dockerfile
        networks:
          - app-network
        depends_on:
          - database

    database:
        build:
          context: ./Database
          dockerfile: Dockerfile
        networks:
          - app-network
        volumes:
          - database-volume:/var/lib/postgresql/data
          

    httpd:
        build:
          context: ./HTTPServer
          dockerfile: Dockerfile
        ports:
          - '80:80'
          - '8080:8080'
        networks:
          - app-network
        depends_on:
          - backend-blue
          - backend-green
    
    front:
        build: 
          context: ./devops-front
          dockerfile: Dockerfile
        networks:
          - app-network
        depends_on:
          - httpd
      
    
networks:
    app-network:
      name: app-network
      external: true

volumes:
    database-volume:
      name: database-volume
      external: true
