---
# tasks file for roles/proxy
  - name: Run HTTPD
    docker_container:
      name: httpd
      image: krouzet/httpserver
      network_mode: app-network
      ports:
        - '80:80'
        - '8080:8080'